---

- name: update apt
  become: true
  apt:
    update_cache: yes

- name: install prerequisite packages
  become: true
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add an Apt signing key, uses whichever key is at the URL
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add beegfs repository to sources list
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: update apt
  become: true
  apt:
    update_cache: yes

- name: install  docker
  become: true
  apt: 
    name: docker-ce
    state: present
    
- name: add user mod
  become: true
  command: usermod -aG docker {{ansible_user}}