---
- name: check pointcloud-tiler directory 
  file: 
    path: '{{home_dir}}/dev/pointcloud-tiler'
    state: directory
  
- name: clone pointcloud-tiler repository 
  expect:
    command: git clone {{ pointcloud_tiler_repository }} {{home_dir}}/dev/pointcloud-tiler
    responses:
          Username: "{{ gitlab_username }}" # Username is a regex
          Password: "{{ gitlab_password }}" # Password is a regex
    timeout: C(null)
  register: clone_result
 #no_log: true

- name: check pointcloud-tiler build directory 
  file: 
    path: '{{home_dir}}/dev/pointcloud-tiler/build/release'
    state: directory
  when: clone_result is succeeded

- name: cmake pointcloud-tiler 
  command: cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS={{home_dir}}/dev/lastools/LASzip/dll -DLASZIP_LIBRARY={{home_dir}}/dev/lastools/LASzip/build/src/liblaszip.so -S {{home_dir}}/dev/pointcloud-tiler/ -B {{home_dir}}/dev/pointcloud-tiler/build/release

# - name: make pointcloud-tiler
#   
#   command: make
#   args: 
#     chdir: '{{home_dir}}/dev/pointcloud-tiler/build/release'